[BB2-1179] Node SDK packaging and publish
CMSgov/cms-bb2-node-sdk pull request #14
Opened 2022-04-11 21:56 UTC by JFU-GIT

**JIRA Ticket:**
[SOMEPROJECT-42](https://jira.cms.gov/browse/SOMEPROJECT-42)

**User Story or Bug Summary:**

### What Does This PR Do?

### What Should Reviewers Watch For?

If you're reviewing this PR, please check these things, in particular:

- TODO

2022-04-14 15:31 UTC, dtisza1 requested changes
@JFU-GIT This is looking good to me!  

Just one change request related to the license file.

Your testing procedure worked for me to produce the package file.

I was able to install it using:

```
$ yarn add file:cms-bluebutton-sdk-0.1.0.tgz 
```
I haven't tried utilizing the SDK yet, though.

Looks good!

2022-04-14 15:31 UTC, dtisza1 commented on LICENSE
> +MIT License
@JFU-GIT This file should be used: https://github.com/CMSgov/cms-open-source-policy/blob/master/LICENSE

2022-04-15 14:47 UTC, dtisza1 approved these changes
@JFU-GIT This looks good to me!

I'll create a separate PR for the license file and also for the other 3x repos.

Good work on this!

2022-04-19 14:30 UTC, oragame reviewed
@JFU-GIT Looks good, I assume the install would not work any more since it was removed from the package repo? Should I try testing anything else before approval?

2022-04-20 14:41 UTC, JFU-GIT commented
> @JFU-GIT Looks good, I assume the install would not work any more since it was removed from the package repo? Should I try testing anything else before approval?

Thanks for review and comments, on npm registry - it's unpublished, so not installable from npm.

to verify what can do is the pack and install locally e.g. npm pack -> get the tar ball, go to the location of the app and yarn add file: <path to tar ball>

2022-04-20 21:34 UTC, oragame commented
> to verify what can do is the pack and install locally e.g. npm pack -> get the tar ball, go to the location of the app and yarn add file:

OH, I understand now... thanks for clearing that up :)

2022-04-20 22:15 UTC, oragame approved these changes
Looks good! was able to test locally after I realized my local node version was outdated. Nice work!

2022-04-21 15:09 UTC, merged